from datetime import datetime, timedelta, timezone

def prepare_mail_body(instance_id, cluster_name, pods):

    # Define IST timezone (UTC+5:30)
    IST = timezone(timedelta(hours=5, minutes=30))
    # Get current time in IST
    timestamp = datetime.now(IST).strftime("%Y-%m-%d %H:%M:%S IST")

    pod_section = (
        "<ul>" + "".join([f"<li>{p}</li>" for p in pods.splitlines() if p.strip()]) + "</ul>"
        if pods else "<p>No pods found or unable to retrieve pod details.</p>"
    )

    body = f"""
    <html>
    <head>
      <style>
        body {{
            font-family: Arial, sans-serif;
            color: #333333;
            line-height: 1.6;
        }}
        h2 {{
            color: #2c3e50;
        }}
        .section {{
            margin-bottom: 20px;
        }}
        .label {{
            font-weight: bold;
        }}
        .footer {{
            margin-top: 30px;
            font-size: 12px;
            color: #777777;
        }}
      </style>
    </head>
    <body>
      <h2>🚨 Spot Instance Interruption Alert</h2>

      <div class="section">
        <p><span class="label">Timestamp:</span> {timestamp}</p>
        <p><span class="label">Cluster Name:</span> {cluster_name}</p>
        <p><span class="label">Instance ID:</span> {instance_id}</p>
      </div>

      <div class="section">
        <h3>Pods Running on Instance</h3>
        {pod_section}
      </div>

      <div class="footer">
        <p>This is an automated notification generated by the Spot Termination Monitoring System.</p>
      </div>
    </body>
    </html>
    """
    return body
